### ISSUE TITLE
Homebrew cask requires sudo but _homebrew is not usual user account with password

### ISSUE THREAD

**Issue by elyulka** [brewdo/brewdo#12]
Trying to run next command:

```
❯ brew cask install araxis-merge
==> We need to make Caskroom for the first time at /opt/homebrew-cask/Caskroom
==> We'll set permissions properly so we won't need sudo in the future

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password:
```

But password "*" does not work, nor my account's password. 

_homebrew user is not in the system list of users,

Tried using `passwd` to change password but no luck.

Is there a way to allow sudo for _homebrew user?

**Comment by telemachus** [comment]
Maybe I'm confused, but if you're using `brewdo`, don't you want this?

    brewdo brew cask install araxis-merge

**Comment by elyulka** [comment]
I'm using recommended alias `brew=brewdo brew`, so its actually running 
`brewdo brew cask install araxis-merge`

**Comment by zigg** [comment]
I stumbled across this issue myself a bit ago, but it wasn't important enough to me to fix it in brewdo at the time.

The right way to add cask support is probably to create a custom brewdo cask command that leverages a root sudo and sets up the `/opt/homebrew-cask` tree correctly. Patches welcome.

The quick-and-dirty fix is probably to create that tree and `chown` it to the `_homebrew` user manually.

**Comment by michaellopez** [comment]
@zigg I stumbled upon this in another fashion. Some casks require `sudo` to install, like [VirtualBox](https://github.com/caskroom/homebrew-cask/blob/master/Casks/virtualbox.rb), I get the same error there. Can't continue with password `*` nor my account password.

**Comment by zigg** [comment]
@michaellopez: I've been thinking about this a bit more. There are two paths forward, I think:

1.  Modify the Homebrew owner to have a password and let it use Sudo to go to root, or just let it Sudo to root without a password.  I hesitate to do this, because it lets operations running as the Homebrew owner escalate universally.  With the password, it's safer, so I might go for that—but it's another password for the system user to maintain.

2.  Drop an escape hatch [here](https://github.com/zigg/brewdo/blob/master/brewdo#L211-L223) so that brewdo doesn't jump to the Homebrew owner at all to do cask operations.  This obviously breaks the brewdo sandbox for cask operations, but maybe it's for the best—if casks require using Sudo to go to root anyway, then the sandbox isn't going to be useful for those casks.

All of this is complicated by the fact that I'm not currently a Cask user. I might be in the future, but not right at the moment. I'd like to lean on some Cask users for advice here.

**Comment by gmkey** [comment]
I'm an avid cask user and I tried brewdo tonight. To be honest: I'm a bit dissapointed, but then I came across this issue and I'm feeling a bit better. 

In reply to your suggested paths:

1. No never. Don't have scripts which intentionally have reduced rights to sudo. It's a disaster waiting to happen. So no escalation. 

2. That sounds better. IMHO I would recommend adding this option. It should be made clear to the end user that he is installing outside of the sandbox, but the whole idea of Casks is to be able to download and install your applications from a repository rather than ten different repositories. 
On my local machine I had previously created a group brew, which had write permissions on my /usr/local, /opt/homebrew-cask/Caskroom/ and other folders. I have just added
````chmod g+w````
to:
/usr/local/bin/
/opt/homebrew-cask/Caskroom/
/usr/local/Library/Taps/

and that seemed to work when using:
````/usr/local/bin/brew cask install <program>````

 Although I'm not sure if it covers every possible option, but it's worth exploring.

**Comment by michaellopez** [comment]
I would like option 2 as well. I agree with @gmkey

**Comment by zigg** [comment]
I've been playing with this a bit today.  Findings so far:

-   We can't just set `cask` to an escape hatch wholesale like I'd hoped. The installation fails because it needs the Homebrew user to install Cask.

-   Starting off by manually tapping and bringing `brew-cask` in, e.g.

    ```
    brew tap caskroom/cask
    brew install brew-cask
    ```

    then using the escape hatch is promising, but I ran into write issues at `/Library/Homebrew/Caches`.

-   I can get around the cache write issues by making `~/Library/Hombrew/Caches`, which will be preferred over `/Library/Homebrew/Caches` if it exists—so the Homebrew user uses the system cache, and your user account uses its own cache.  `virtualbox` now installs, being a package installer.

-   But `packer` doesn't install, because it isn't a package installer—it wants to symlink to `/usr/local/bin`. `packer` *will* install with `--no-binaries`, but then of course it doesn't have binaries on our `PATH`. There are a *lot* of Casks with `binary` resources and not a real simple way to clean up after not permitting Cask to deal with this.

I get the impression that Cask and brewdo aren't a great fit for each other, just due to the kind of software Cask installs (vs. Homebrew's typical package, which is an easy slide to the pattern brewdo uses.)

**Comment by zigg** [comment]
I've pushed (`feature/cask-escape-hatch`)[https://github.com/zigg/brewdo/compare/feature/cask-escape-hatch], so feel free to play with it.

I'm not totally sure what I want to do with this, yet. It should be relatively easy to intercept a `brew cask` command and make sure Cask is tapped/installed before proceeding, but I'd like some more confidence in this solution before doing that.

**Comment by alexreg** [comment]
Okay, after much deliberation, I've decided that putting a notice on brewdo's install that the user should set a password for the _homebrew user if they want to user cask, is the cleanest, simplest, and most secure solution. If anyone has any objections, feel free to reply, but I'm closing the issue for now.
